### PR TITLE
Static pages integrated on rails app :)

### PR DESCRIPTION
**Pull request by rabingaire**

### CODE REVIEW

**Comment by takehiromouri** [comment]
Awesome job integrating the template into the Rails app @rabingaire !

One thing I noticed - instead of `StaticpagesController.rb`, let's make them camelcase (`StaticPagesController`). Same goes for the other controllers as well :) You'll have some renaming to do, but this will follow the convention that a lot of Rails developers follow, so let's fix this up a bit :)

Other than that, it looks good! 👍

**Comment by rabingaire** [comment]
I fixed it @takehiromouri  :)

**Comment by takehiromouri** [comment]
Awesome! :)

Also let's make `formpages.html` into `form_pages.html` :) 

In this case, `formpages.html` is readable, but `form_pages.html` is very slightly easier to read :) In this case, it's not a big deal, but it's always a good habit of making our naming the easiest to understand/read :)

**Comment by takehiromouri** [comment]
Ahh sorry for the misconfusion @rabingaire - instead of making the html file camelcase, let's make it underscore (`form_pages.html` instead of `FormPages.html`).

This is a very small nuance and not to be super nit-picky, but it seems like a lot of developers prefer underscore for HTML and JS files, as well as JS classnames etc. Same goes for ruby method names etc.

It's really small, so it's no big deal, but still a good habit to have in my opinion :)

**Comment by rabingaire** [comment]
Ok I will do that haha i thought it would be nice idea :) @takehiromouri

**Comment by takehiromouri** [comment]
Awesome! Looks good to go! :shipit: (this is the ship it squirrel :P)

**Comment by swojeet** [comment]
Good to merge :+1:

**Comment by sthpravin** [comment]
its good

**Pull request merged**
