### PR TITLE
Rails actionmailer

### PR DESCRIPTION
**Pull request by swojeet**

### CODE REVIEW

**Comment by rabingaire** [comment]
@swojeet could you please add the .travis.yml file to this branch :) The file is in master branch just update your code and again push it to github :)

**Comment by swojeet** [comment]
Updated my master branch and pushed it again @rabingaire :)

**Comment by takehiromouri** [comment]
@swojeet Let's pull the recent version from the master branch :) Once we do that let's merge this branch in.

**Comment by swojeet** [comment]
@takehiromouri pulled it and pushed it again :) shall we merge it ?

**Comment by takehiromouri** [comment]
Looks good to me 👍

**Comment by rabingaire** [comment]
let's merge :)

**Comment by sthpravin** [comment]
:+1:

**Pull request merged**
